name: Generate Build on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
          VITE_SUPABASE_PROJECT: ${{ secrets.VITE_SUPABASE_PROJECT }}

      - name: Push to prod
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: prod
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: "Build: ${{ github.sha }}"